name: Testing

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - master
  #too many minutes
  #schedule:
  #  - cron:  '17 1 * * *' # Run every day on a seemly random time.

jobs:
  test:
    uses: wp-cli/.github/.github/workflows/reusable-testing.yml@main
    with:
      minimum-php: '7.1'
      minimum-wp: '6.1'
    strategy:
      matrix:
        exclude:
          - coverage: true