name: Testing

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - master
  #too many minutes
  #schedule:
  #  - cron:  '17 1 * * *' # Run every day on a seemly random time.

jobs:
  test:
    uses: trepmal/.github-test/.github/workflows/reusable-testing.yml@add/coverage-input
    with:
      minimum-php: '7.1'
      minimum-wp: '6.1'
      with-coverage: false